# Generated by Django 5.0 on 2026-05-08 16:58

import apuntes_pdf.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_registro_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApuntesPDF',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf', models.FileField(upload_to=apuntes_pdf.models.pdf_upload_path)),
                ('pdf_url', models.URLField(blank=True, default='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.registro')),
            ],
        ),
    ]
