# Generated by Django 5.0 on 2026-05-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apuntes_pdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessagePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apunte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='apuntes_pdf.apuntespdf')),
            ],
        ),
    ]
