# Generated by Django 5.2.13 on 2026-05-02 06:52

import subida_cursos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubidaCurso',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending to Start'), ('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to=subida_cursos.models.video_upload_path)),
                ('video_url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
