# Generated by Django 5.0 on 2026-05-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registro_language'),
        ('subida_cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subidacurso',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.registro'),
        ),
    ]
