# Generated by Django 5.0 on 2026-05-11 08:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subida_cursos', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subidacurso',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
    ]
