# Generated by Django 5.0 on 2026-05-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('pt', 'Português')], default='en', max_length=2),
        ),
    ]
