# Generated by Django 5.0 on 2026-05-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registro_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
